# Base directory for the build
[build]
  publish = "out" # Next.js exports to 'out' directory when output: 'export' is used
  command = "npm run build && npm run export" # Command to build and export the Next.js app

# Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' *.supabase.co; frame-src 'self' *.supabase.co;"
    Cache-Control = "public, max-age=0, must-revalidate"

# Specific headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (optional, can be set in Netlify UI)
[context.production.environment]
  # NEXT_PUBLIC_SUPABASE_URL = "your_supabase_url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key"
